service: serverless-iot-cam-alexaskill
frameworkVersion: ">=1.34.0 <2.0.0"
provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  environment:
    BUCKET_NAME: ${file(env.yml):BUCKET_NAME}
    IMAGE_NAME: ${file(env.yml):IMAGE_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource: "arn:aws:s3:::${file(env.yml):BUCKET_NAME}"
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::${file(env.yml):BUCKET_NAME}/${file(env.yml):IMAGE_NAME}"
    - Effect: Allow
      Action:
        - rekognition:RecognizeCelebrities
      Resource: "*"

functions:
  AlexaSkillHandler:
    handler: index.handler
    timeout: 3
    events:
      - alexaSkill: ${file(env.yml):ALEXA_SKILL_ID}

package:
  exclude:
    - .vscode
    - .serverless
